### ISSUE TITLE
Incorrect display of Cyrillic font in utf-8

### ISSUE THREAD

**Issue by cynodesmus** [NeonKnightOA/unreal-localization#13]
The code page in UTF-8 is not suitable for the correct display of the Russian translation in the game. Anyway, with the 227i patch installed.
utf-8:
![utf-8_1](https://user-images.githubusercontent.com/16974509/120822452-7af34a00-c567-11eb-9aba-fb7274ce75e7.png)
![utf-8_2](https://user-images.githubusercontent.com/16974509/120822461-7cbd0d80-c567-11eb-8a43-e9ea47382093.png)
In any case, this is the situation with the Cyrillic font. Perhaps the same problem with all non-Latin characters.

Correct display in the game, occurs with the code page files UTF-16Le.
utf-16le:
![utf-16le_1](https://user-images.githubusercontent.com/16974509/120823860-ea1d6e00-c568-11eb-8668-4a84d542d621.png)
![utf-16le_2](https://user-images.githubusercontent.com/16974509/120823868-ebe73180-c568-11eb-8144-5c3199637021.png)

P.S. The Russian translation files present in patch 227i are also encoded in UTF-16Le.

**Comment by NeonKnightOA** [comment]
Unfortunately, this is more of a problem with U1 itself and the way it parses UTF16-LE than the project.

The files in the localizaton repo are encoded under UTF-8 with BOM.

**Comment by cynodesmus** [comment]
Yes, perhaps I was too hasty to ask issues.
Also, in the general piggy bank of knowledge: during the file-by-file conversion in the editor of the FAR file manager - I managed to get a workable translation file.
However, when using third-party applications for batch converting files, although the encoding was changed, the files were not perceived by the game.

This is more suitable for an informational message, for those who will work with these files in the future.

**Comment by NeonKnightOA** [comment]
Have you tried the files in this repository? They're located in the `Unreal/SystemLocalized` folder, some are there and others in `Unreal/SystemLocalized/WIP-Templates/Russian`. They require A LOT of work (and the already finished strings in the Wiki put in there), though.

**Comment by cynodesmus** [comment]
Yes, I watched them. They are workable. I thought they were in patch 227?
In general, I was driven by curiosity - to see what the difference is between the translations.

Also, files in the directory: Unreal/SystemLocalized/WIP-Templates/Russian - are in 16Le encoding - do not convert them to UTF-8

**Comment by NeonKnightOA** [comment]
Patch v227i has an unfinished version, RTNP isn't translated for example.

I just finished Italian yesterday. Once I finish French, Deutsch and Polish (which have contributors waiting), I'll tackle Russian. But if you want to help, here's the procedure I use:

- Base files located in `Unreal(Tournament)\SystemLocalized\WIP-Templates\Russian`, finished files in `Unreal(Tournament)\SystemLocalized`
- The lines from `Unreal(Tournament)\SystemLocalized\WIP-Templates\Unrealv227\Russian` must be pasted on top of those from `Unreal(Tournament)\SystemLocalized\WIP-Templates\Russian`, unless a line is better, that's up to the localizator. Once that's done, the same must be done with the .rut files in the Wiki (the pages are located under https://www.oldunreal.com/wiki/index.php?title=Russian_.rut/Unreal for Unreal and https://www.oldunreal.com/wiki/index.php?title=Russian_.rut/UT for UT, some of these pages have shared files or sections, I still need to wikify those). Why? Because with help at an all-time low, I'd rather have two ways of working and let people choose which method they like to work with.
- The `[Public]` sections must be checked so all the trees concord. In order to keep track of this, we have the Language Guidelines, which for the Russian language must be completed and checked here: https://www.oldunreal.com/wiki/index.php?title=Russian_.rut/Language_Guidelines .
- Once all of the hard work is done, we test in-game in order to find inconsistencies or errors and fix them.

**Comment by cynodesmus** [comment]
Okay, I'll read the material and try to provide all the help I can.

**Comment by NeonKnightOA** [comment]
Excellent! Let me know if you need help with anything. 🍻

**Comment by cynodesmus** [comment]
A little earlier, I found in Steam a link to a modified version of the Russian translation for patch 227i.
The annotation indicated a site where you can contact some of the authors of the translation ... I'm trying to contact them, as this would go faster (in my opinion).
P.S. Now summer is difficult with free time. Pandemic, replacement of people on sick leave and those who went on vacation ... so the process will take a little longer.

**Comment by NeonKnightOA** [comment]
Take your time. I'm also dealing with a lot of RL issues too.
